### ISSUE TITLE
Cannot read property 'log' of undefined -- variable "runtime" of init node-red

### ISSUE THREAD

**Issue by dlopezrodriguez** [ibmets/node-red-bluemix-starter#22]
Hello ,

I was tha app run perfectly about three month ago and now i have this problem:::::::::

2018-02-28T11:06:33.02+0100 [APP/PROC/WEB/0] OUT 28 Feb 10:06:33 - Loading application settings
2018-02-28T11:06:33.04+0100 [APP/PROC/WEB/0] ERR /home/vcap/app/node_modules/node-red/red/runtime/storage/localfilesystem/projects/index.js:45
2018-02-28T11:06:33.04+0100 [APP/PROC/WEB/0] ERR     log = runtime.log;
2018-02-28T11:06:33.04+0100 [APP/PROC/WEB/0] ERR                  ^
2018-02-28T11:06:33.04+0100 [APP/PROC/WEB/0] ERR TypeError: Cannot read property 'log' of undefined
2018-02-28T11:06:33.04+0100 [APP/PROC/WEB/0] ERR     at Object.init (/home/vcap/app/node_modules/node-red/red/runtime/storage/localfilesystem/projects/index.js:45:18)
2018-02-28T11:06:33.04+0100 [APP/PROC/WEB/0] ERR     at Object.init (/home/vcap/app/node_modules/node-red/red/runtime/storage/localfilesystem/index.js:62:32)
2018-02-28T11:06:33.04+0100 [APP/PROC/WEB/0] ERR     at Object.<anonymous> (/home/vcap/app/index.js:87:13)
2018-02-28T11:06:33.04+0100 [APP/PROC/WEB/0] ERR     at Module._compile (module.js:570:32)
2018-02-28T11:06:33.04+0100 [APP/PROC/WEB/0] ERR     at Object.Module._extensions..js (module.js:579:10)
2018-02-28T11:06:33.04+0100 [APP/PROC/WEB/0] ERR     at Module.load (module.js:487:32)
2018-02-28T11:06:33.04+0100 [APP/PROC/WEB/0] ERR     at tryModuleLoad (module.js:446:12)
2018-02-28T11:06:33.04+0100 [APP/PROC/WEB/0] ERR     at Function.Module._load (module.js:438:3)
2018-02-28T11:06:33.04+0100 [APP/PROC/WEB/0] ERR     at Module.runMain (module.js:604:10)
2018-02-28T11:06:33.04+0100 [APP/PROC/WEB/0] ERR     at run (bootstrap_node.js:383:7)
2018-02-28T11:06:33.08+0100 [APP/PROC/WEB/0] ERR npm ERR! Linux 4.4.0-109-generic
2018-02-28T11:06:33.08+0100 [APP/PROC/WEB/0] ERR npm ERR! argv "/home/vcap/app/vendor/node/bin/node" "/home/vcap/app/vendor/node/bin/npm" "start"
2018-02-28T11:06:33.08+0100 [APP/PROC/WEB/0] ERR npm ERR! node v6.12.3
2018-02-28T11:06:33.08+0100 [APP/PROC/WEB/0] ERR npm ERR! npm  v3.10.10
2018-02-28T11:06:33.08+0100 [APP/PROC/WEB/0] ERR npm ERR! code ELIFECYCLE
2018-02-28T11:06:33.08+0100 [APP/PROC/WEB/0] ERR npm ERR! shell-service-app@0.6.0 start: `node --max-old-space-size=384 index.js --settings ./bluemix-settings.js -v`
2018-02-28T11:06:33.08+0100 [APP/PROC/WEB/0] ERR npm ERR! Exit status 1
2018-02-28T11:06:33.08+0100 [APP/PROC/WEB/0] ERR npm ERR!
2018-02-28T11:06:33.08+0100 [APP/PROC/WEB/0] ERR npm ERR! Failed at the shell-service-app@0.6.0 start script 'node --max-old-space-size=384 index.js --settings ./bluemix-settings.js -v'.
2018-02-28T11:06:33.08+0100 [APP/PROC/WEB/0] ERR npm ERR! Make sure you have the latest version of node.js and npm installed.
2018-02-28T11:06:33.08+0100 [APP/PROC/WEB/0] ERR npm ERR! If you do, this is most likely a problem with the shell-service-app package,
2018-02-28T11:06:33.08+0100 [APP/PROC/WEB/0] ERR npm ERR! not with npm itself.
2018-02-28T11:06:33.08+0100 [APP/PROC/WEB/0] ERR npm ERR! Tell the author that this fails on your system:
2018-02-28T11:06:33.08+0100 [APP/PROC/WEB/0] ERR npm ERR!     node --max-old-space-size=384 index.js --settings ./bluemix-settings.js -v
2018-02-28T11:06:33.08+0100 [APP/PROC/WEB/0] ERR npm ERR! You can get information on how to open an issue for this project with:
2018-02-28T11:06:33.08+0100 [APP/PROC/WEB/0] ERR npm ERR!     npm bugs shell-service-app
2018-02-28T11:06:33.08+0100 [APP/PROC/WEB/0] ERR npm ERR! Or if that isn't available, you can get their info via:
2018-02-28T11:06:33.08+0100 [APP/PROC/WEB/0] ERR npm ERR!     npm owner ls shell-service-app
2018-02-28T11:06:33.08+0100 [APP/PROC/WEB/0] ERR npm ERR! There is likely additional logging output above.
2018-02-28T11:06:33.09+0100 [APP/PROC/WEB/0] ERR npm ERR! Please include the following file with any support request:
2018-02-28T11:06:33.09+0100 [APP/PROC/WEB/0] ERR npm ERR!     /home/vcap/app/npm-debug.log

**Comment by knolleary** [comment]
It will have hit this because it could not find your cloudant storage instance used by the app. Has it been renamed or deleted? There will have been a log message further up indicating this.

Obviously it is unfortunate to hit an error in this scenario - and we'll fit it in the core node-red, but even if it started up, without cloudant in place, it won't have access to your flow data.

**Comment by dlopezrodriguez** [comment]
Hello knolleary ,
thanks for answering.

This logs is before:::

2018-02-28T11:04:46.55+0100 [APP/PROC/WEB/0] OUT Exit status 1
2018-02-28T11:04:46.55+0100 [CELL/0] OUT Exit status 0
2018-02-28T11:04:46.56+0100 [CELL/0] OUT Stopping instance f225b4dc-b3f3-4303-6a55-f9e6
2018-02-28T11:04:46.56+0100 [CELL/0] OUT Destroying container
2018-02-28T11:04:47.29+0100 [API/5] OUT Process has crashed with type: "web"
2018-02-28T11:04:47.39+0100 [API/5] OUT App instance exited with guid ff1e0226-19ef-4629-88cd-2d71b2409e59 payload: {"instance"=>"f225b4dc-b3f3-4303-6a55-f9e6", "index"=>0, "reason"=>"CRASHED", "exit_description"=>"APP/PROC/WEB: Exited with status 1", "crash_count"=>4, "crash_timestamp"=>1519812286542860126, "version"=>"7e8fdf5d-ace0-49f0-bccc-6641ec984c37"}
2018-02-28T11:04:48.90+0100 [CELL/0] OUT Successfully destroyed container
2018-02-28T11:06:09.99+0100 [CELL/0] OUT Creating container
2018-02-28T11:06:11.31+0100 [CELL/0] OUT Successfully created container
2018-02-28T11:06:30.32+0100 [CELL/0] OUT Starting health monitoring of container
2018-02-28T11:06:32.01+0100 [APP/PROC/WEB/0] OUT > shell-service-app@0.6.0 start /home/vcap/app
2018-02-28T11:06:32.01+0100 [APP/PROC/WEB/0] OUT > node --max-old-space-size=384 index.js --settings ./bluemix-settings.js -v
2018-02-28T11:06:32.63+0100 [APP/PROC/WEB/0] OUT 28 Feb 10:06:32 - Starting Node-RED on Bluemix bootstrap
2018-02-28T11:06:32.64+0100 [APP/PROC/WEB/0] OUT 28 Feb 10:06:32 - Loading bluemix-settings.js
2018-02-28T11:06:32.71+0100 [APP/PROC/WEB/0] OUT 28 Feb 10:06:32 - Failed to find Cloudant service: /^dev-shell-service.cloudantNoSQLDB/
2018-02-28T11:06:33.02+0100 [APP/PROC/WEB/0] OUT 28 Feb 10:06:33 - Loading application settings

**Comment by knolleary** [comment]
```
Failed to find Cloudant service: /^dev-shell-service.cloudantNoSQLDB/
```

So, it is expecting to find a cloudant service called `dev-shell-service.cloudantNoSQLDB`. What cloudant service have you got bound to the app?

**Comment by dlopezrodriguez** [comment]
That log service problem came from file:: bluemix-settings.js ::  line 85 ,
but before of runtime problem, the app run "ok" with that service error log.

**Comment by knolleary** [comment]
Just to be clear, you were running without cloudant attached so you were not saving your flows anywhere? Any restart of the app would lose them.

**Comment by dlopezrodriguez** [comment]
Ok , you are right I solved this problem creating this CloudantNoSQLDB Service.

But now, I have the same problem on the localhost node server, but this can be a connection problem with cloudant because it does not find the service when, this created.

Thanks for your help.
